traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

#
# Service Locator - Consul
#
service-locator:
  image: progrium/consul
  container_name: consul
  hostname: consul
  restart: always
  #command: "-server -bootstrap -advertise $DOCKER_IP -log-level debug"
  command: "-server -bootstrap -advertise 172.17.0.1"
  ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
#
# Service Discovery - Registrator
#
#service-discovery:
#  image: gliderlabs/registrator
#  container_name: registrator
#  hostname: registrator
#  restart: always
  # -ip <ip address>   Force IP address used for registering services
#  command: -ip=172.17.0.1 consul://consul:8500
#  links:
#  - service-locator
#  volumes:
#  - "/var/run/docker.sock:/tmp/docker.sock"
  #net: "host"

helloService:
  image: training/helloservice
  labels:
    - "traefik.backend=hello"
    - "traefik.frontend.rule=Path:/v1/hello"
  ports:
    - 9001:9000

helloGreeting:
  image: training/greetingservice
  labels:
    - "traefik.backend=greeting"
    - "traefik.frontend.rule=Path:/v1/greeting"
  links:
    - helloService
  ports:
    - 9002:9000
