version: '2'
 
services:
  #
  # Load Balancer/Gateway - HAProxy
  #
  service-gateway:
    build: ./haproxy/
    restart: always
    container_name: haproxy
    hostname: haproxy
    links:
    - service-locator
    ports:
    - "9000:9000" # WebApp (not used)
    - "9001:9001" # Service 1
    - "9002:9002" # Service 2
    - "1936:1936" # Statistics
  #
  # Service Locator - Consul
  #
  service-locator:
    image: progrium/consul
    container_name: consul
    hostname: consul
    restart: always
    #command: "-server -bootstrap -advertise $DOCKER_IP -log-level debug"
    command: "-server -bootstrap -advertise 172.17.0.1"
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
  #
  # Service Discovery - Registrator
  #
  service-discovery:
    image: gliderlabs/registrator
    container_name: registrator
    hostname: registrator
    restart: always
    # -ip <ip address>   Force IP address used for registering services
    command: -ip=172.17.0.1 consul://consul:8500
    links:
    - service-locator
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    #net: "host"
  #
  # Backend
  #
  backend-hello:
    image: training/helloservice
    hostname: backend-hello
    environment:
      SERVICE_TAGS: backend
      SERVICE_NAME: helloservice
    ports:
      - 9000

  backend-greeting:
    image: training/greetingservice
    hostname: backend-greeting
    links:
     - backend-hello
    environment:
      SERVICE_TAGS: backend
      SERVICE_NAME: greetingservice
    ports:
      - 9000
